filetype plugin indent on
syntax enable

set backspace=start,eol,indent
set hidden

" Use only ~/.vim as runtime path
let $RTP=split(&runtimepath, ',')[0]
" Set path to our vimrc
let $RC="$HOME/.vim/vimrc"

set path-=/usr/include
set complete-=i
set wildmenu
set wildmode=longest:full,full
set wildignore+=*DS_Store*
set wildignore+=*/.git/*
set wildignore+=*/.vagrant/*
set wildignore+=*/node_modules/*

set noswapfile nowritebackup
set incsearch ignorecase smartcase
set hlsearch
set showmatch
set shiftwidth=8 tabstop=8 softtabstop=8 noexpandtab autoindent smartindent

set splitbelow
set splitright
set ttyfast
set lazyredraw
set scrolloff=10
set encoding=utf-8
set ruler
